# hardware-configuration.nix
# Generated by nixos-generate-config and extended with tmpfs root.
#
# Partition layout expected on disk:
#   /dev/disk/by-label/ESP    → FAT32   → /boot/efi  (~512 MB)
#   /dev/disk/by-label/NIX    → ext4    → /nix        (~20 GB)
#   /dev/disk/by-label/PERSIST→ ext4    → /persist    (~10 GB)
#   (none)                    → tmpfs   → /            (RAM, 2 GB cap)
#
# To use UUIDs instead of labels, replace device = "/dev/disk/by-label/..."
# with device = "/dev/disk/by-uuid/YOUR-UUID".

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # ── Root: ephemeral tmpfs ───────────────────────────────────────────────────
  # The root filesystem lives entirely in RAM and is wiped on every reboot.
  # Nothing here survives unless explicitly declared in modules/impermanence.nix.
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "defaults"
      "size=2G"   # Increase if you run memory-hungry root-level services
      "mode=755"  # Required by several daemons (e.g. openssh)
    ];
  };

  # ── /nix: immutable Nix store ───────────────────────────────────────────────
  # All packages and their closures live here, read-only after activation.
  # Replace the label/UUID to match your actual partition.
  fileSystems."/nix" = {
    device = "/dev/disk/by-label/NIX";
    fsType = "ext4";
    options = [ "defaults" "relatime" ];
    neededForBoot = true;
  };

  # ── /persist: durable state ─────────────────────────────────────────────────
  # Only directories/files explicitly declared in impermanence.nix are
  # bind-mounted from here into the ephemeral root at boot time.
  fileSystems."/persist" = {
    device = "/dev/disk/by-label/PERSIST";
    fsType = "ext4";
    options = [ "defaults" "relatime" ];
    neededForBoot = true;
  };

  # ── /boot/efi: EFI System Partition ────────────────────────────────────────
  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-label/ESP";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  # ── Swap (optional) ─────────────────────────────────────────────────────────
  # Uncomment and set your swap partition/file if needed.
  # swapDevices = [ { device = "/dev/disk/by-label/SWAP"; } ];

  # ── Hardware / CPU ──────────────────────────────────────────────────────────
  # nixos-generate-config will fill these in automatically.
  # Listed here as stubs so the file is valid without running generate-config.
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # Change to "kvm-amd" on AMD systems
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
